"use client";

import { useEffect, useRef, useState } from "react";

const HOURS = Array.from({ length: 12 }, (_, index) => index + 1);
const MINUTES = Array.from({ length: 12 }, (_, index) => index * 5);
function partsOf(time: string) { const [hours = "09", minutes = "00"] = time.split(":"); return { hour: Number(hours), minute: Number(minutes) }; }

export function TimePicker({ label, timeName }: { label: string; timeName: string }) {
  const rootRef = useRef<HTMLDivElement>(null); const [isOpen, setIsOpen] = useState(false); const [step, setStep] = useState<"hour" | "minute">("hour"); const [value, setValue] = useState(""); const [draft, setDraft] = useState("09:00");
  const parts = partsOf(draft); const isPm = parts.hour >= 12; const displayHour = parts.hour % 12 || 12; const selected = step === "hour" ? displayHour : parts.minute;
  useEffect(() => { function close(event: MouseEvent) { if (rootRef.current && !rootRef.current.contains(event.target as Node)) setIsOpen(false); } document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  function setMeridiem(pm: boolean) { setDraft(`${String((parts.hour % 12) + (pm ? 12 : 0)).padStart(2, "0")}:${String(parts.minute).padStart(2, "0")}`); }
  function choose(number: number) { if (step === "hour") { setDraft(`${String((number % 12) + (isPm ? 12 : 0)).padStart(2, "0")}:${String(parts.minute).padStart(2, "0")}`); setStep("minute"); } else setDraft(`${String(parts.hour).padStart(2, "0")}:${String(number).padStart(2, "0")}`); }
  return <div className="time-only-picker" ref={rootRef}><input type="hidden" name={timeName} value={value} /><button type="button" className={`time-only-trigger ${isOpen ? "is-open" : ""}`} onClick={() => { setDraft(value || "09:00"); setStep("hour"); setIsOpen(open => !open); }}><span aria-hidden="true">◷</span><span><small>{label}</small><strong>{value || "Choisir une heure"}</strong></span><i aria-hidden="true">⌄</i></button>{isOpen && <div className="time-only-popover"><div className="clock-picker"><div className="clock-title">SELECT TIME</div><div className="clock-display"><button type="button" className={step === "hour" ? "active" : ""} onClick={() => setStep("hour")}>{String(displayHour).padStart(2, "0")}</button><span>:</span><button type="button" className={step === "minute" ? "active" : ""} onClick={() => setStep("minute")}>{String(parts.minute).padStart(2, "0")}</button><div><button type="button" className={!isPm ? "active" : ""} onClick={() => setMeridiem(false)}>AM</button><button type="button" className={isPm ? "active" : ""} onClick={() => setMeridiem(true)}>PM</button></div></div><div className="clock-face"><i className="clock-hand" style={{ transform: `rotate(${(selected % 12) * 30}deg)` }} /><span className="clock-center" />{(step === "hour" ? HOURS : MINUTES).map((number, index) => <button key={number} type="button" className={number === selected ? "selected" : ""} style={{ transform: `rotate(${index * 30}deg) translateY(-84px) rotate(${-index * 30}deg)` }} onClick={() => choose(number)}>{step === "minute" ? String(number).padStart(2, "0") : number}</button>)}</div><div className="clock-actions"><button type="button" onClick={() => setIsOpen(false)}>CANCEL</button><button type="button" onClick={() => { setValue(draft); setIsOpen(false); }}>OK</button></div></div></div>}</div>;
}
